import { randomBytes, randomUUID } from 'node:crypto';
import { errorMessage } from '../../utils';
import {
  createApplication,
  removeApplication,
  uniqueSlug,
  updateVariableValue,
} from '../applications/application.service';
import type { CreateApplicationDTO } from '../applications/application.schema';
import { findHostPortConflict } from '../applications/port-guard.service';
import { parseComposeDocument, publishedPortsOf } from '../compose/compose.service';
import { enqueueDeployment } from '../deployments/pipeline.service';
import { allTemplates } from './catalog.service';
import { parseEnvContent, renderTemplate, type RenderTemplateContext } from './render.service';
import type {
  DeployTemplateDTO,
  ListTemplatesQuery,
  TemplateSecretGenerator,
} from './template.schema';

export const findTemplateById = (templateId: string): Template | undefined =>
  allTemplates().find(template => template.id === templateId);

const matchesSearch = (template: Template, search?: string) => {
  if (!search) {
    return true;
  }

  const needle = search.trim().toLowerCase();

  return (
    template.name.toLowerCase().includes(needle) ||
    template.tagline.toLowerCase().includes(needle) ||
    template.tags.some(tag => tag.toLowerCase().includes(needle))
  );
};

const matchesCategory = (template: Template, category?: string) =>
  !category || template.category === category;

export const listTemplates = ({
  search,
  category,
  page,
  size,
}: ListTemplatesQuery & { page: number; size: number }) => {
  const filtered = allTemplates().filter(
    template =>
      !template.deprecated &&
      matchesSearch(template, search) &&
      matchesCategory(template, category),
  );

  const skip = (page - 1) * size;
  const items = filtered.slice(skip, skip + size);

  return {
    items: items.map(serializeTemplate),
    total: filtered.length,
    page,
    size,
    pages: Math.max(1, Math.ceil(filtered.length / size)),
  };
};

export const serializeTemplate = (template: Template) => ({
  id: template.id,
  version: template.version,
  name: template.name,
  tagline: template.tagline,
  category: template.category,
  tags: template.tags,
  icon: template.icon,
  website: template.website,
  documentation: template.documentation,
  license: template.license,
  author: template.author,
  origin: template.origin,
  deprecated: template.deprecated,
  expose: template.expose,
  databases: template.databases,
  inputs: template.inputs,
  secrets: template.secrets.map(secret => ({ key: secret.key, generate: secret.generate })),
});

const PASSWORD_ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789';
const PASSWORD_LENGTH = 24;
const HEX32_BYTES = 16;

export const generateSecretValue = (generator: TemplateSecretGenerator): string => {
  if (generator === 'password') {
    return Array.from(
      randomBytes(PASSWORD_LENGTH),
      byte => PASSWORD_ALPHABET[byte % PASSWORD_ALPHABET.length],
    ).join('');
  }

  if (generator === 'hex32') {
    return randomBytes(HEX32_BYTES).toString('hex');
  }

  return randomUUID();
};

export const regenerateTemplateSecret = async (application: Application, key: string) => {
  if (application.source !== 'compose' || !application.origin?.templateId) {
    throw new Error('This application was not created from a template');
  }

  const template = findTemplateById(application.origin.templateId);
  const secret = template?.secrets.find(candidate => candidate.key === key);

  if (!secret) {
    throw new Error(`"${key}" is not a generated secret of this application's template`);
  }

  const value = generateSecretValue(secret.generate);

  await updateVariableValue(String(application._id), key, value);
};

export const deployTemplateApplication = async (params: {
  template: Template;
  organizationId: string;
  projectId: string;
  server: Server;
  body: DeployTemplateDTO;
  triggeredBy: string;
}) => {
  const { template, organizationId, projectId, server, body, triggeredBy } = params;

  const secretKeys = new Set(template.secrets.map(secret => secret.key));

  for (const key of Object.keys(body.inputs)) {
    if (secretKeys.has(key)) {
      throw new Error(`"${key}" is generated by the server and cannot be provided as an input`);
    }
  }

  const secretValues = Object.fromEntries(
    template.secrets.map(secret => [secret.key, generateSecretValue(secret.generate)]),
  );

  const slug = await uniqueSlug(body.environmentId, body.name);

  const context: RenderTemplateContext = {
    applicationSlug: slug,
    serverHost: server.agent.host ?? server.ssh.host,
  };

  const { composeYaml, env } = renderTemplate(
    template,
    { ...body.inputs, ...secretValues },
    context,
  );

  const parsed = parseComposeDocument(composeYaml);
  const conflict = await findHostPortConflict(String(server._id), publishedPortsOf(parsed));

  if (conflict) {
    throw new Error(`Host port ${conflict.port} is already in use by ${conflict.owner}`);
  }

  const variables = parseEnvContent(env).map(({ key, value }) => ({
    key,
    value,
    secret: secretKeys.has(key),
  }));

  const applicationBody: CreateApplicationDTO = {
    source: 'compose',
    name: body.name,
    environmentId: body.environmentId,
    serverId: String(server._id),
    compose: {
      content: composeYaml,
      expose: { service: template.expose.service, port: template.expose.port },
    },
    variables,
    restartPolicy: 'unless-stopped',
  };

  let application: Application | undefined;

  try {
    application = await createApplication(organizationId, projectId, applicationBody, {
      slug,
      origin: { templateId: template.id, templateVersion: template.version, inputs: body.inputs },
    });

    const deployment = body.deployNow
      ? await enqueueDeployment({ application, trigger: 'manual', triggeredBy })
      : undefined;

    return { application, deployment };
  } catch (error) {
    if (!application) {
      throw error instanceof Error ? error : new Error(String(error));
    }

    try {
      await removeApplication(String(application._id));
    } catch (cleanupError) {
      throw new Error(
        `Failed to deploy template "${template.id}" (${errorMessage(error)}), and cleaning up ` +
          `also failed: application ${application._id} was left behind (${errorMessage(cleanupError)})`,
      );
    }

    throw error instanceof Error ? error : new Error(String(error));
  }
};
