#!/usr/bin/env bash

set -euo pipefail

ZYDOCK_INSTALL_DIR="${ZYDOCK_INSTALL_DIR:-/data/zydock}"
ZYDOCK_REPO="${ZYDOCK_REPO:-https://github.com/zylelabs/zydock.git}"
ZYDOCK_CHANNEL="${ZYDOCK_CHANNEL:-}"
ZYDOCK_BRANCH="${ZYDOCK_BRANCH:-}"
ZYDOCK_DOMAIN="${ZYDOCK_DOMAIN:-}"
ZYDOCK_HOST="${ZYDOCK_HOST:-}"
ZYDOCK_SUPERUSER_EMAIL="${ZYDOCK_SUPERUSER_EMAIL:-}"

log() { printf '\n\033[1;36m▸ %s\033[0m\n' "$1"; }
warn() { printf '\n\033[1;33m⚠ %s\033[0m\n' "$1" >&2; }
fail() {
  printf '\n\033[1;31m✖ %s\033[0m\n' "$1" >&2
  exit 1
}

ensure_env() {
  local key="$1" value="$2"

  grep -q "^${key}=" .env 2>/dev/null || printf '%s="%s"\n' "${key}" "${value}" >>.env
}

set_env() {
  local key="$1" value="$2"

  if grep -q "^${key}=" .env 2>/dev/null; then
    sed -i "s|^${key}=.*|${key}=\"${value}\"|" .env
  else
    printf '%s="%s"\n' "${key}" "${value}" >>.env
  fi
}

channel_branch() {
  case "$1" in
  stable) echo "main" ;;
  nightly) echo "nightly" ;;
  dev) echo "dev" ;;
  *) echo "$1" ;;
  esac
}

channel_ref() {
  if [ "$1" != "stable" ]; then
    echo "origin/$(channel_branch "$1")"
    return
  fi

  local tag
  tag="$(git tag --list 'v*' | { grep -Ev -- '-' || true; } | sort -V | tail -n1)"

  if [ -n "${tag}" ]; then
    echo "${tag}"
  else
    echo "origin/main"
  fi
}

migrate_port_urls() {
  [ -f .env ] || return 0

  . ./.env
  local changed=false

  case "${APP_URL:-}" in
  *:3000)
    set_env APP_URL "${APP_URL%:3000}"
    changed=true
    ;;
  esac

  case "${CORS_ORIGIN:-}" in
  *:3000)
    set_env CORS_ORIGIN "${CORS_ORIGIN%:3000}"
    changed=true
    ;;
  esac

  case "${NUXT_PUBLIC_WS_URL:-}" in
  *:8000/api/ws)
    set_env NUXT_PUBLIC_WS_URL "${NUXT_PUBLIC_WS_URL%:8000/api/ws}/api/ws"
    changed=true
    ;;
  esac

  if [ "${changed}" = true ]; then
    log "Migrated .env off the published :3000/:8000 URLs"
  fi
}

if [ -z "${ZYDOCK_CHANNEL}" ] && [ -n "${ZYDOCK_BRANCH}" ]; then
  case "${ZYDOCK_BRANCH}" in
  main) ZYDOCK_CHANNEL="stable" ;;
  *) ZYDOCK_CHANNEL="${ZYDOCK_BRANCH}" ;;
  esac
fi

CHANNEL="${ZYDOCK_CHANNEL:-stable}"
BRANCH="$(channel_branch "${CHANNEL}")"

[ "$(id -u)" -eq 0 ] || fail "Run as root (or with sudo)."
command -v apt-get >/dev/null 2>&1 || fail "This installer only supports Debian/Ubuntu (needs apt-get)."

log "Installing prerequisites"

if ! command -v git >/dev/null 2>&1 || ! command -v openssl >/dev/null 2>&1 || ! command -v curl >/dev/null 2>&1; then
  apt-get update -qq
  DEBIAN_FRONTEND=noninteractive apt-get install -y -qq git openssl curl
fi

if ! command -v docker >/dev/null 2>&1; then
  curl -fsSL https://get.docker.com -o /tmp/zydock-get-docker.sh
  sh /tmp/zydock-get-docker.sh
  rm -f /tmp/zydock-get-docker.sh
  systemctl enable --now docker
fi

docker compose version >/dev/null 2>&1 || fail "Docker was installed but the 'docker compose' plugin is missing."

log "Fetching Zydock (${CHANNEL}) into ${ZYDOCK_INSTALL_DIR}"

if [ ! -d "${ZYDOCK_INSTALL_DIR}/.git" ]; then
  if [ -d "${ZYDOCK_INSTALL_DIR}" ] && [ -n "$(ls -A "${ZYDOCK_INSTALL_DIR}")" ]; then
    fail "${ZYDOCK_INSTALL_DIR} already exists and is not a Zydock install. Remove it or set ZYDOCK_INSTALL_DIR."
  fi

  mkdir -p "$(dirname "${ZYDOCK_INSTALL_DIR}")"
  git clone --branch "${BRANCH}" "${ZYDOCK_REPO}" "${ZYDOCK_INSTALL_DIR}"
fi

cd "${ZYDOCK_INSTALL_DIR}"

git fetch --tags origin "${BRANCH}"
# This directory is a deployed instance, not a workspace: any local edit is discarded on update.
git reset --hard "$(channel_ref "${CHANNEL}")"

if [ ! -f .env ]; then
  log "Generating secrets"

  ZYDOCK_HOST="${ZYDOCK_HOST:-$(curl -fsS https://api.ipify.org || true)}"
  [ -n "${ZYDOCK_HOST}" ] || [ -n "${ZYDOCK_DOMAIN}" ] || fail "Could not autodetect the public IP — set ZYDOCK_HOST or ZYDOCK_DOMAIN explicitly."

  ZYDOCK_SUPERUSER_EMAIL="${ZYDOCK_SUPERUSER_EMAIL:-admin@${ZYDOCK_DOMAIN:-zydock.local}}"

  MONGO_USERNAME="zydock"
  MONGO_PASSWORD="$(openssl rand -hex 24)"
  JWT_SECRET="$(openssl rand -hex 32)"
  ENCRYPTION_KEY="$(openssl rand -hex 32)"
  LOCAL_AGENT_TOKEN="$(openssl rand -hex 32)"

  if [ -n "${ZYDOCK_DOMAIN}" ]; then
    APP_URL="https://${ZYDOCK_DOMAIN}"
    WS_URL="wss://${ZYDOCK_DOMAIN}/api/ws"
  else
    APP_URL="http://${ZYDOCK_HOST}"
    WS_URL="ws://${ZYDOCK_HOST}/api/ws"
  fi

  cat >.env <<EOF
# Generated by scripts/install.sh on $(date -u +%FT%TZ) — keep this file secret and back it up.
MODE="prod"
CORS_ORIGIN="${APP_URL}"
APP_URL="${APP_URL}"
BACKEND_URL="http://backend:8000"

MONGO_USERNAME="${MONGO_USERNAME}"
MONGO_PASSWORD="${MONGO_PASSWORD}"
MONGO_URI="mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/zydock?authSource=admin"

JWT_SECRET="${JWT_SECRET}"
ENCRYPTION_KEY="${ENCRYPTION_KEY}"
LOCAL_AGENT_TOKEN="${LOCAL_AGENT_TOKEN}"

SUPERUSER_EMAILS="${ZYDOCK_SUPERUSER_EMAIL}"

ZYDOCK_DOMAIN="${ZYDOCK_DOMAIN}"
PUBLIC_IP="${ZYDOCK_HOST}"
URL_API="http://backend:8000"
NUXT_PUBLIC_WS_URL="${WS_URL}"
EOF

  chmod 600 .env
else
  log "Existing install found — reusing .env, updating in place"
  ensure_env LOCAL_AGENT_TOKEN "$(openssl rand -hex 32)"
  ensure_env PUBLIC_IP "$(curl -fsS https://api.ipify.org || true)"
  migrate_port_urls
fi

export ZYDOCK_CHANNEL="${CHANNEL}"

set_env ZYDOCK_VERSION "$(bash scripts/version.sh)"
set_env ZYDOCK_COMMIT "$(bash scripts/version.sh commit)"
set_env ZYDOCK_CHANNEL "${CHANNEL}"
set_env ZYDOCK_INSTALL_DIR "${ZYDOCK_INSTALL_DIR}"

. ./.env

COMPOSE_ARGS=(-f docker-compose.prod.yml --env-file .env)

docker network inspect zydock >/dev/null 2>&1 || docker network create zydock

log "Building and starting the stack"
docker compose "${COMPOSE_ARGS[@]}" up -d --build

log "Waiting for the backend to become healthy"
ATTEMPTS=0
until [ "$(docker compose "${COMPOSE_ARGS[@]}" ps --format '{{.Health}}' backend)" = "healthy" ]; do
  ATTEMPTS=$((ATTEMPTS + 1))
  [ "${ATTEMPTS}" -le 60 ] || fail "Backend did not become healthy in time. Check: docker compose -f docker-compose.prod.yml logs backend"
  sleep 2
done

log "Checking that the containers can reach GitHub"
GITHUB_CHECK="$(docker compose "${COMPOSE_ARGS[@]}" exec -T backend bun -e 'try { const r = await fetch("https://api.github.com/", { signal: AbortSignal.timeout(10000) }); console.log(r.ok ? "ok" : "http"); } catch { const dns = await import("node:dns/promises"); try { await dns.lookup("api.github.com"); console.log("egress"); } catch { console.log("dns"); } }' </dev/null 2>/dev/null | tr -d '\r' | tail -n1)"

case "${GITHUB_CHECK}" in
ok) ;;
dns)
  warn "The containers cannot resolve api.github.com — deploys from GitHub will fail.
  Give the Docker daemon an explicit resolver and restart it:
    echo '{ \"dns\": [\"1.1.1.1\", \"8.8.8.8\"] }' >/etc/docker/daemon.json && systemctl restart docker"
  ;;
egress)
  warn "The containers resolve api.github.com but cannot connect to it — deploys from GitHub will fail.
  The name resolves, so this is outbound filtering: check 'iptables -S DOCKER-USER', the FORWARD
  chain policy and any firewall of your provider."
  ;;
*)
  warn "Could not check GitHub connectivity from the backend container. If deploys fail at the
  clone step, run: docker compose -f docker-compose.prod.yml exec backend sh -c 'getent hosts api.github.com'"
  ;;
esac

log "Provisioning the superadmin account and the default organization"
SEED_OUTPUT="$(docker compose "${COMPOSE_ARGS[@]}" exec -T backend bun run seed </dev/null 2>&1)" || true
echo "${SEED_OUTPUT}"
TEMP_PASSWORD="$(echo "${SEED_OUTPUT}" | grep -o 'temporary password: [^"]*' | head -n1 | sed 's/temporary password: //' || true)"

log "Done"
echo "Zydock ${ZYDOCK_VERSION} (channel: ${CHANNEL})"
echo "Dashboard: ${APP_URL}"
if [ -n "${TEMP_PASSWORD}" ]; then
  echo "Superadmin: ${SUPERUSER_EMAILS}"
  echo "Temporary password (shown once): ${TEMP_PASSWORD}"
else
  echo "Superadmin account already existed — no new password generated."
fi
echo
echo "Re-run this script anytime to update Zydock (git pull + rebuild); secrets are kept."
