#!/usr/bin/env bash

set -euo pipefail

ZYDOCK_INSTALL_DIR="${ZYDOCK_INSTALL_DIR:-/data/zydock}"
ZYDOCK_REPO="${ZYDOCK_REPO:-https://github.com/zylelabs/zydock.git}"
ZYDOCK_BRANCH="${ZYDOCK_BRANCH:-main}"
ZYDOCK_DOMAIN="${ZYDOCK_DOMAIN:-}"
ZYDOCK_HOST="${ZYDOCK_HOST:-}"
ZYDOCK_SUPERUSER_EMAIL="${ZYDOCK_SUPERUSER_EMAIL:-}"

log() { printf '\n\033[1;36m▸ %s\033[0m\n' "$1"; }
fail() {
  printf '\n\033[1;31m✖ %s\033[0m\n' "$1" >&2
  exit 1
}

ensure_env() {
  local key="$1" value="$2"

  grep -q "^${key}=" .env 2>/dev/null || printf '%s="%s"\n' "${key}" "${value}" >>.env
}

[ "$(id -u)" -eq 0 ] || fail "Run as root (or with sudo)."
command -v apt-get >/dev/null 2>&1 || fail "This installer only supports Debian/Ubuntu (needs apt-get)."

log "Installing prerequisites"

if ! command -v git >/dev/null 2>&1 || ! command -v openssl >/dev/null 2>&1 || ! command -v curl >/dev/null 2>&1; then
  apt-get update -qq
  DEBIAN_FRONTEND=noninteractive apt-get install -y -qq git openssl curl
fi

if ! command -v docker >/dev/null 2>&1; then
  curl -fsSL https://get.docker.com -o /tmp/zydock-get-docker.sh
  sh /tmp/zydock-get-docker.sh
  rm -f /tmp/zydock-get-docker.sh
  systemctl enable --now docker
fi

docker compose version >/dev/null 2>&1 || fail "Docker was installed but the 'docker compose' plugin is missing."

log "Fetching Zydock into ${ZYDOCK_INSTALL_DIR}"

if [ -d "${ZYDOCK_INSTALL_DIR}/.git" ]; then
  git -C "${ZYDOCK_INSTALL_DIR}" fetch origin "${ZYDOCK_BRANCH}"
  # This directory is a deployed instance, not a workspace: any local edit is discarded on update.
  git -C "${ZYDOCK_INSTALL_DIR}" reset --hard "origin/${ZYDOCK_BRANCH}"
elif [ -d "${ZYDOCK_INSTALL_DIR}" ] && [ -n "$(ls -A "${ZYDOCK_INSTALL_DIR}")" ]; then
  fail "${ZYDOCK_INSTALL_DIR} already exists and is not a Zydock install. Remove it or set ZYDOCK_INSTALL_DIR."
else
  mkdir -p "$(dirname "${ZYDOCK_INSTALL_DIR}")"
  git clone --branch "${ZYDOCK_BRANCH}" "${ZYDOCK_REPO}" "${ZYDOCK_INSTALL_DIR}"
fi

cd "${ZYDOCK_INSTALL_DIR}"

if [ ! -f .env ]; then
  log "Generating secrets"

  ZYDOCK_HOST="${ZYDOCK_HOST:-$(curl -fsS https://api.ipify.org || true)}"
  [ -n "${ZYDOCK_HOST}" ] || [ -n "${ZYDOCK_DOMAIN}" ] || fail "Could not autodetect the public IP — set ZYDOCK_HOST or ZYDOCK_DOMAIN explicitly."

  ZYDOCK_SUPERUSER_EMAIL="${ZYDOCK_SUPERUSER_EMAIL:-admin@${ZYDOCK_DOMAIN:-zydock.local}}"

  MONGO_USERNAME="zydock"
  MONGO_PASSWORD="$(openssl rand -hex 24)"
  JWT_SECRET="$(openssl rand -hex 32)"
  ENCRYPTION_KEY="$(openssl rand -hex 32)"
  LOCAL_AGENT_TOKEN="$(openssl rand -hex 32)"

  if [ -n "${ZYDOCK_DOMAIN}" ]; then
    APP_URL="https://${ZYDOCK_DOMAIN}"
    WS_URL="wss://${ZYDOCK_DOMAIN}/api/ws"
    BIND_HOST="127.0.0.1"
  else
    APP_URL="http://${ZYDOCK_HOST}:3000"
    WS_URL="ws://${ZYDOCK_HOST}:8000/api/ws"
    BIND_HOST="0.0.0.0"
  fi

  cat >.env <<EOF
# Generated by scripts/install.sh on $(date -u +%FT%TZ) — keep this file secret and back it up.
MODE="prod"
CORS_ORIGIN="${APP_URL}"
APP_URL="${APP_URL}"
BACKEND_URL="http://backend:8000"

MONGO_USERNAME="${MONGO_USERNAME}"
MONGO_PASSWORD="${MONGO_PASSWORD}"
MONGO_URI="mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/zydock?authSource=admin"

JWT_SECRET="${JWT_SECRET}"
ENCRYPTION_KEY="${ENCRYPTION_KEY}"
LOCAL_AGENT_TOKEN="${LOCAL_AGENT_TOKEN}"

SUPERUSER_EMAILS="${ZYDOCK_SUPERUSER_EMAIL}"

ZYDOCK_DOMAIN="${ZYDOCK_DOMAIN}"
BIND_HOST="${BIND_HOST}"
URL_API="http://backend:8000"
NUXT_PUBLIC_WS_URL="${WS_URL}"
EOF

  chmod 600 .env
else
  log "Existing install found — reusing .env, updating in place"
  ensure_env LOCAL_AGENT_TOKEN "$(openssl rand -hex 32)"
fi

. ./.env

COMPOSE_ARGS=(-f docker-compose.prod.yml --env-file .env)

docker network inspect zydock >/dev/null 2>&1 || docker network create zydock

log "Building and starting the stack"
docker compose "${COMPOSE_ARGS[@]}" up -d --build

log "Waiting for the backend to become healthy"
ATTEMPTS=0
until [ "$(docker compose "${COMPOSE_ARGS[@]}" ps --format '{{.Health}}' backend)" = "healthy" ]; do
  ATTEMPTS=$((ATTEMPTS + 1))
  [ "${ATTEMPTS}" -le 60 ] || fail "Backend did not become healthy in time. Check: docker compose -f docker-compose.prod.yml logs backend"
  sleep 2
done

log "Provisioning the superadmin account and the default organization"
SEED_OUTPUT="$(docker compose "${COMPOSE_ARGS[@]}" exec -T backend bun run seed 2>&1)" || true
echo "${SEED_OUTPUT}"
TEMP_PASSWORD="$(echo "${SEED_OUTPUT}" | grep -o 'temporary password: [^"]*' | head -n1 | sed 's/temporary password: //')"

log "Done"
echo "Dashboard: ${APP_URL}"
if [ -n "${TEMP_PASSWORD}" ]; then
  echo "Superadmin: ${SUPERUSER_EMAILS}"
  echo "Temporary password (shown once): ${TEMP_PASSWORD}"
else
  echo "Superadmin account already existed — no new password generated."
fi
echo
echo "Re-run this script anytime to update Zydock (git pull + rebuild); secrets are kept."
