#!/usr/bin/env bash
#
# Zydock — self-hosted installer.
#
# Installs the whole control plane (MongoDB + backend + frontend, and Caddy when a domain is
# given) on a clean Ubuntu/Debian server, via Docker Compose. Running it again on an existing
# install updates it in place (git pull + rebuild) without touching the secrets already generated.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/zylelabs/zydock/main/scripts/install.sh | sudo bash
#
# Environment variables (all optional):
#   ZYDOCK_INSTALL_DIR      Where to clone the repo.                  Default: /data/zydock
#   ZYDOCK_REPO             Git URL to clone.                         Default: https://github.com/zylelabs/zydock.git
#   ZYDOCK_BRANCH           Branch to check out.                      Default: main
#   ZYDOCK_DOMAIN           Public domain for the dashboard. When set, Caddy is started in front
#                            of the stack and issues an HTTPS certificate for it automatically.
#   ZYDOCK_HOST             Public host/IP used to reach the dashboard when ZYDOCK_DOMAIN is not
#                            set (the frontend and the WebSocket are reachable there on :3000 and
#                            :8000).                                  Default: autodetected public IP
#   ZYDOCK_SUPERUSER_EMAIL  Email of the first superadmin account.    Default: admin@<domain, or
#                            zydock.local when there is none — a bare IP is not a valid email>
#
# On the first run this generates JWT_SECRET, ENCRYPTION_KEY and the MongoDB credentials into
# <install-dir>/.env. That file is the only place they are stored — back it up.

set -euo pipefail

ZYDOCK_INSTALL_DIR="${ZYDOCK_INSTALL_DIR:-/data/zydock}"
ZYDOCK_REPO="${ZYDOCK_REPO:-https://github.com/zylelabs/zydock.git}"
ZYDOCK_BRANCH="${ZYDOCK_BRANCH:-main}"
ZYDOCK_DOMAIN="${ZYDOCK_DOMAIN:-}"
ZYDOCK_HOST="${ZYDOCK_HOST:-}"
ZYDOCK_SUPERUSER_EMAIL="${ZYDOCK_SUPERUSER_EMAIL:-}"

log() { printf '\n\033[1;36m▸ %s\033[0m\n' "$1"; }
fail() {
  printf '\n\033[1;31m✖ %s\033[0m\n' "$1" >&2
  exit 1
}

[ "$(id -u)" -eq 0 ] || fail "Run as root (or with sudo)."
command -v apt-get >/dev/null 2>&1 || fail "This installer only supports Debian/Ubuntu (needs apt-get)."

log "Installing prerequisites"

if ! command -v git >/dev/null 2>&1 || ! command -v openssl >/dev/null 2>&1 || ! command -v curl >/dev/null 2>&1; then
  apt-get update -qq
  DEBIAN_FRONTEND=noninteractive apt-get install -y -qq git openssl curl
fi

if ! command -v docker >/dev/null 2>&1; then
  curl -fsSL https://get.docker.com -o /tmp/zydock-get-docker.sh
  sh /tmp/zydock-get-docker.sh
  rm -f /tmp/zydock-get-docker.sh
  systemctl enable --now docker
fi

docker compose version >/dev/null 2>&1 || fail "Docker was installed but the 'docker compose' plugin is missing."

log "Fetching Zydock into ${ZYDOCK_INSTALL_DIR}"

FIRST_INSTALL=true

if [ -d "${ZYDOCK_INSTALL_DIR}/.git" ]; then
  FIRST_INSTALL=false
  git -C "${ZYDOCK_INSTALL_DIR}" fetch origin "${ZYDOCK_BRANCH}"
  # This directory is a deployed instance, not a workspace: any local edit is discarded on update.
  git -C "${ZYDOCK_INSTALL_DIR}" reset --hard "origin/${ZYDOCK_BRANCH}"
else
  mkdir -p "$(dirname "${ZYDOCK_INSTALL_DIR}")"
  git clone --branch "${ZYDOCK_BRANCH}" "${ZYDOCK_REPO}" "${ZYDOCK_INSTALL_DIR}"
fi

cd "${ZYDOCK_INSTALL_DIR}"

if [ -f .env ]; then
  FIRST_INSTALL=false
fi

if [ "${FIRST_INSTALL}" = true ]; then
  log "Generating secrets"

  ZYDOCK_HOST="${ZYDOCK_HOST:-$(curl -fsS https://api.ipify.org || true)}"
  [ -n "${ZYDOCK_HOST}" ] || [ -n "${ZYDOCK_DOMAIN}" ] || fail "Could not autodetect the public IP — set ZYDOCK_HOST or ZYDOCK_DOMAIN explicitly."

  # The backend's email validation rejects a bare IP as the domain part, so a host-only install
  # (no ZYDOCK_DOMAIN) falls back to a placeholder domain instead of "admin@<ip>".
  ZYDOCK_SUPERUSER_EMAIL="${ZYDOCK_SUPERUSER_EMAIL:-admin@${ZYDOCK_DOMAIN:-zydock.local}}"

  MONGO_USERNAME="zydock"
  MONGO_PASSWORD="$(openssl rand -hex 24)"
  JWT_SECRET="$(openssl rand -hex 32)"
  ENCRYPTION_KEY="$(openssl rand -hex 32)"

  if [ -n "${ZYDOCK_DOMAIN}" ]; then
    APP_URL="https://${ZYDOCK_DOMAIN}"
    WS_URL="wss://${ZYDOCK_DOMAIN}/api/ws"
  else
    APP_URL="http://${ZYDOCK_HOST}:3000"
    WS_URL="ws://${ZYDOCK_HOST}:8000/api/ws"
  fi

  cat >.env <<EOF
# Generated by scripts/install.sh on $(date -u +%FT%TZ) — keep this file secret and back it up.
MODE="prod"
CORS_ORIGIN="${APP_URL}"
APP_URL="${APP_URL}"
BACKEND_URL="http://backend:8000"

MONGO_USERNAME="${MONGO_USERNAME}"
MONGO_PASSWORD="${MONGO_PASSWORD}"
MONGO_URI="mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/zydock?authSource=admin"

JWT_SECRET="${JWT_SECRET}"
ENCRYPTION_KEY="${ENCRYPTION_KEY}"

SUPERUSER_EMAILS="${ZYDOCK_SUPERUSER_EMAIL}"

ZYDOCK_DOMAIN="${ZYDOCK_DOMAIN}"
NUXT_URL_API="http://backend:8000"
NUXT_PUBLIC_WS_URL="${WS_URL}"
EOF

  chmod 600 .env
else
  log "Existing install found — reusing .env, updating in place"
fi

# shellcheck disable=SC1091
. ./.env

COMPOSE_ARGS=(-f docker-compose.prod.yml --env-file .env)
[ -n "${ZYDOCK_DOMAIN:-}" ] && COMPOSE_ARGS+=(--profile domain)

log "Building and starting the stack"
docker compose "${COMPOSE_ARGS[@]}" up -d --build

log "Waiting for the backend to become healthy"
ATTEMPTS=0
until [ "$(docker compose "${COMPOSE_ARGS[@]}" ps --format '{{.Health}}' backend)" = "healthy" ]; do
  ATTEMPTS=$((ATTEMPTS + 1))
  [ "${ATTEMPTS}" -le 60 ] || fail "Backend did not become healthy in time. Check: docker compose -f docker-compose.prod.yml logs backend"
  sleep 2
done

log "Provisioning the superadmin account"
SEED_OUTPUT="$(docker compose "${COMPOSE_ARGS[@]}" exec -T backend bun run seed 2>&1)" || true
echo "${SEED_OUTPUT}"
TEMP_PASSWORD="$(echo "${SEED_OUTPUT}" | grep -o 'temporary password: [^"]*' | head -n1 | sed 's/temporary password: //')"

log "Done"
echo "Dashboard: ${APP_URL}"
if [ -n "${TEMP_PASSWORD}" ]; then
  echo "Superadmin: ${SUPERUSER_EMAILS}"
  echo "Temporary password (shown once): ${TEMP_PASSWORD}"
else
  echo "Superadmin account already existed — no new password generated."
fi
echo
echo "Re-run this script anytime to update Zydock (git pull + rebuild); secrets are kept."
